/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package numberSystems;
import java.util.*;
import java.util.Arrays;

/**
 *
 * @author evrob0095
 */
public class numberSystems extends javax.swing.JFrame {

    /**
     * Creates new form numberSystems
     */
    public numberSystems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dToH = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bdInput = new javax.swing.JTextField();
        dbInput = new javax.swing.JTextField();
        toDecimalButton = new javax.swing.JButton();
        toBinaryButton = new javax.swing.JButton();
        dhInput = new javax.swing.JTextField();
        hdInput = new javax.swing.JTextField();
        toHexButton = new javax.swing.JButton();
        toDecimalButton2 = new javax.swing.JButton();
        dToB = new javax.swing.JLabel();
        decimalBinaryLabel = new javax.swing.JLabel();
        binaryDecimalLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dToH.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        dToH.setText("Decimal & Hexidecimal");
        jPanel1.add(dToH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        title.setFont(new java.awt.Font("Stencil Std", 0, 18)); // NOI18N
        title.setText("Number System Converter");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        jLabel3.setText("Hexidecimal Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        bdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdInputActionPerformed(evt);
            }
        });
        jPanel1.add(bdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, -1));

        dbInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInputActionPerformed(evt);
            }
        });
        jPanel1.add(dbInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 70, -1));

        toDecimalButton.setText("Convert to Decimal");
        toDecimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDecimalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toDecimalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 150, -1));

        toBinaryButton.setText("Convert to Binary");
        toBinaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBinaryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toBinaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 150, -1));

        dhInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhInputActionPerformed(evt);
            }
        });
        jPanel1.add(dhInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, -1));

        hdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdInputActionPerformed(evt);
            }
        });
        jPanel1.add(hdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 70, -1));

        toHexButton.setText("Convert to Hexidecimal");
        toHexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHexButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toHexButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 150, -1));

        toDecimalButton2.setText("Convert to Decimal");
        toDecimalButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDecimalButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(toDecimalButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 150, -1));

        dToB.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        dToB.setText("Decimal & Binary");
        jPanel1.add(dToB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        decimalBinaryLabel.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        decimalBinaryLabel.setText("Decimal Number");
        jPanel1.add(decimalBinaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        binaryDecimalLabel.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        binaryDecimalLabel.setText("Binary Number");
        jPanel1.add(binaryDecimalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        jLabel7.setText("Decimal Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdInputActionPerformed

    private void dbInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbInputActionPerformed

    private void toDecimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDecimalButtonActionPerformed
        String input = bdInput.getText();
        int decimal = Integer.parseInt(input,2);
        bdInput.setText(decimal + "");
    }//GEN-LAST:event_toDecimalButtonActionPerformed

    private void dhInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dhInputActionPerformed

    private void hdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hdInputActionPerformed

    private void toDecimalButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDecimalButton2ActionPerformed
        String hex = hdInput.getText();
        int decimal;
        decimal = Integer.parseInt(hex, 16);
        hdInput.setText(decimal +"");
    }//GEN-LAST:event_toDecimalButton2ActionPerformed

    private void toHexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toHexButtonActionPerformed
        int decimal = Integer.parseInt(dhInput.getText());
        String hex = "";
        char [] hexToDec = new char [100];
        int i = 0;
        while (decimal != 0) {
            int temp = 0;
            temp = decimal % 16;
            if (temp < 10) {
                hexToDec[i] = (char)(temp+48);
                i++;
            }
            else {
                hexToDec[i] = (char)(temp+55);
                i++;
            }
            decimal = decimal/16;
        }
        for(int j=i-1; j>=0; j--) {
            hex = hex + hexToDec[j];
            dhInput.setText(hex);
            System.out.println(hex);
        } 
    }//GEN-LAST:event_toHexButtonActionPerformed

    private void toBinaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBinaryButtonActionPerformed
        String input = dbInput.getText();
        int index = 0;
        int decimal;
        String binary = "";
        int newRevBinary[] = new int [20];
        decimal = Integer.parseInt(input);
        while (decimal > 0) {
            newRevBinary[index++] = decimal %2;
            decimal = decimal/2;
        }
        for (int i = index - 1; i >= 0; i--) {
            binary = binary + newRevBinary[i];
        }
        dbInput.setText(binary);
        
    }//GEN-LAST:event_toBinaryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(numberSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(numberSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(numberSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(numberSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numberSystems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bdInput;
    private javax.swing.JLabel binaryDecimalLabel;
    private javax.swing.JLabel dToB;
    private javax.swing.JLabel dToH;
    private javax.swing.JTextField dbInput;
    private javax.swing.JLabel decimalBinaryLabel;
    private javax.swing.JTextField dhInput;
    private javax.swing.JTextField hdInput;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    private javax.swing.JButton toBinaryButton;
    private javax.swing.JButton toDecimalButton;
    private javax.swing.JButton toDecimalButton2;
    private javax.swing.JButton toHexButton;
    // End of variables declaration//GEN-END:variables
}
